config:
    use_colors: False
    send_anonymous_usage_stats: False

gitbook:
  outputs:
    test:
      type: bigquery
      method: service-account-json
      project: gitbook-dwh
      dataset: marketing_dwh_test
      threads: 5
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      keyfile_json:
        type: "service_account"
        project_id: "gitbook-dwh"
        private_key_id: "..."
        private_key: "{{ env_var('DBT_PROFILE_SA_PK') }}"
        client_email: ".....iam.gserviceaccount.com"
        client_id: "12345"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/..."
    prod:
      type: bigquery
      method: service-account-json
      project: gitbook-dwh
      dataset: marketing_dwh_v1
      threads: 5
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      keyfile_json:
        type: "service_account"
        project_id: "gitbook-dwh"
        private_key_id: "..."
        private_key: "{{ env_var('DBT_PROFILE_SA_PK') }}"
        client_email: "...data.iam.gserviceaccount.com"
        client_id: "67890"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/..."
  target: test
